added logic which enables you to do only backup a part of pods

diff --git a/.github/workflows/backup-kubernetes-databases-inhouse.yml b/.github/workflows/backup-kubernetes-databases-inhouse.yml
--- a/.github/workflows/backup-kubernetes-databases-inhouse.yml
+++ b/.github/workflows/backup-kubernetes-databases-inhouse.yml
@@ -30,6 +30,16 @@ on:
         default: 'https://tkg.dev.bratislava.sk'
         required: true
         type: string
+      ratio:
+        description: 'Ratio for splitting number od pods for a given processing'
+        default: 1
+        required: false
+        type: number
+      part:
+        description: 'Which part of split pods should be processed based on the ratio.'
+        default: 1
+        required: false
+        type: number
     secrets:
       service-account:
         description: 'Kubernetes service account'
@@ -90,14 +100,35 @@ jobs:
 
       - name: Run database backup
         id: dbbackup
-        run: |    
+        run: |
+          if [[ ${{ inputs.part }} -le ${{ inputs.ratio }} ]]; then
+              echo "Error: part (${{ inputs.part }}) is bigger then ratio (${{ inputs.ratio }})";
+              exit 1;
+          fi
+          
           echo "Starting..."
           backup="${{ inputs.backup }}"
           echo "We are going to backup: ${backup}"
           
           # we have different selects for postgress apps and for wordpress
           if [[ "$backup" == "shared-wordpress" ]]; then label="app.kubernetes.io/name=wordpress"; else label="service=database"; fi
-          select=$(kubectl get pod --namespace "${{ inputs.namespace }}" --insecure-skip-tls-verify --request-timeout=5s --selector "$label" --output jsonpath='{.items..metadata.name}')
+          preselect=$(kubectl get pod --namespace "${{ inputs.namespace }}" --insecure-skip-tls-verify --request-timeout=5s --selector "$label" --output jsonpath='{.items..metadata.name}')
+         
+          # Option to process just part of the pods by providing two variables
+          # ratio - split to results to X parts
+          # part - which part should be displayed
+          #
+          # Like to process first half of results, you set ratio to 2 and part to 1. To proceess second half of that set part to 2
+          # If you dont want to split the results, set ratio to 1 and part to 1
+          
+          # count number of pods
+          count=$(echo $preselect | wc -l)
+          
+          # split results based on ratio
+          split=$((count / ${{ inputs.ratio }}))
+          
+          # skips the first X of splits, then display the next split
+          select=$(echo $preselect | tail -n +$(( (${{ inputs.part }} - 1) * split + 1)) | head -n $split) 
           
           # for wordpress we need to check if maria db is running
           if [[ "$backup" == "shared-wordpress" ]]; then 
