skipping a reviewdog fails and makes a pipeline to run till an end

diff --git a/.github/workflows/validate-nest-prisma-inhouse.yml b/.github/workflows/validate-nest-prisma-inhouse.yml
--- a/.github/workflows/validate-nest-prisma-inhouse.yml
+++ b/.github/workflows/validate-nest-prisma-inhouse.yml
@@ -85,7 +85,12 @@ jobs:
           workdir: ${{ inputs.directory }}/src
 
       - name: Typescript check
+        # Review dog will fail when pull request has more than 300 changed files.
+        # We want that next typescript check will do its job for all files
+        # https://stackoverflow.com/questions/58858429/how-to-run-a-github-actions-step-even-if-the-previous-step-fails-while-still-f
+        if: success() || failure()
         run: npx tsc
 
       - name: ESlint check
+        if: success() || failure()
         run: npm run lint
